language: r
sudo: false
cache: packages

r:
 - 3.3
 - 3.4
 - 3.5
 - release
 - devel
 - oldrel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

env:
  global:
  - _R_CHECK_SYSTEM_CLOCK_="FALSE"
